### ISSUE TITLE
Ignition replace - example

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fcct#114]
If I have a YAML file such as https://hackmd.io/lX41BH4TSlqDGqgwr_xWVg?view#Standard-YAML--Igninition-file-for-testing and then update the `version` to `1.1.0` + add `ignition` object with `replace` will it replace the entire ignition file? (I want this feature)  I could not get a good read on this with the current documentation.  My YAML is already in version control and merge will be hard for us to maintain.

Another question is what is the correct way to include a internal version tracking number in the same YAML/ignition?  This will be for our debugging purposes.

**Comment by bgilbert** [comment]
Yes, `replace` replaces the entire Ignition file, and it works with both 1.0.0 and 1.1.0.  But I'm not sure I understand the part about version control and merging.  What are you trying to accomplish?

Re your second question, I'd suggest having Ignition write a file (maybe `/etc/config-version`) with your version number.  That way you can tell which config a system was installed from.

**Comment by shivarammysore** [comment]
I have an Ignition file, say `install_basic.ign` (as referenced earlier).  FCOS has already been installed with the above.  Now, I made changes in the corresponding YAML file with other services and the I add `ignition` object to the same `install_basic.yaml` file

```yaml
variant: fcos
version: 1.1.0
ignition:
  config:
    replace:
      - source: http://10.20.5.7/install_basic.ign
```

```console
$ ~/bin/fcct install_basic.yaml -o install_basic.ign -p
Error translating config: yaml: unmarshal errors:
  line 6: cannot unmarshal !!seq into v0_2.Resource
```
What am I missing?

Also, what is the correct way to inject this ignition to FCOS? `coreos-installer` does not have the relevant options that I could use.

**Comment by bgilbert** [comment]
A config can only have one `replace` directive, so it's not a list.

```yaml
variant: fcos
version: 1.1.0
ignition:
  config:
    replace:
      source: http://10.20.5.7/install_basic.ign
```

Are you trying to update the config on an existing machine?  Ignition is specifically designed not to support that; the config is processed only once, on the first boot.  If you want to change your config, you should reinstall or reprovision the machine using the new config.

The purpose of the `replace` directive is to support stub configs.  For example, on AWS, instance userdata is limited to 16 KB, so you can have a config like the one above that pulls the real config from a network location that doesn't have size limits.

**Comment by shivarammysore** [comment]
Yes - I am trying to update a config on an existing machine.  I don't have network size limits.

How do I "re-provision" an existing machine?  The net effect of my "replace" is basically that.  Specifically what command do I need to use?

**Comment by bgilbert** [comment]
If you're running on bare metal, boot from the live PXE or ISO image and rerun coreos-installer with the new config, exactly as you did the first time.  If you're running in the cloud, launch new instances with the new config and then terminate the old ones.

**Comment by shivarammysore** [comment]
Ok - basically it is a re-install.  Thanks @bgilbert
