### ISSUE TITLE
Clean up exported API

### ISSUE THREAD

**Issue by bgilbert** [coreos/fcct#115]
There are a lot of layers.  It's not clear when external callers should use a particular layer, and some of the layers may not be useful at all.

For example, in the versioned `config` packages, `TranslateBytes` takes a byte slice and returns a byte slice.  If the caller wants to pass in parsed FCC structs, or receive parsed Ignition structs, they might decide to call `Translate` instead.  But the only way to get validation (other than copypasting a bunch of boilerplate) is to use `TranslateBytes`.

We should document the intended use of the API.  Which functions are intended for external use?  Should users ever call directly into `base`?

**Comment by yuqi-zhang** [comment]
In the MCO use case, we have a lot of template files in yaml format that we'd like to transpile into ignition spec 3 configs. We did not know to use `TranslateBytes`, and it would also be nice to skip the byte conversion back and forth if such API was available.
