### ISSUE TITLE
Would symbolic file-modes be useful?

### ISSUE THREAD

**Issue by waisbrot** [coreos/fcct#122]
While [getting some help from dustymabe](https://discussion.fedoraproject.org/t/ignition-file-is-only-partially-read-how-do-i-debug/22247/2?u=waisbrot) on the forums, I learned that the FCC `mode` value needs to be proceeded by a `0`  so that it will be interpreted as an octal value. In a shell, I might type `chmod 444 config`. to give make it world-readable. But in an FCC file if I wrote `mode: 444` I'd get a file with octal mode 674 -- user write and group write+execute.

Another YAML-using system that deals with file-modes is Ansible. Its [file modules](https://docs.ansible.com/ansible/latest/modules/copy_module.html#parameter-mode) offers several options:
- integers, the same as fcct
- strings of integers, which Ansible interprets as octals (so `'444'` is interpreted like `0444` would be)
- "symbolic" modes, such as `'a=r'` and `'a=x,u+rw,g=rx'`

Would this be worth trying? I haven't written much Go, but I'd be interested in trying to implement this if it has potential to be accepted. I implemented the string-as-octal-number easily. The symbolic mode (which is what I'd really like) looks much more complex (though maybe someone's done it already in some Go library). I'm not sure if it's possible to accept both string and integer with the current yaml library.

**Comment by jlebon** [comment]
Not a fan of "strings of integers" because it just makes things more confusing (because now 444 is different from "444").

To start with, I wonder if we should just warn whenever a mode is used *not* in octal mode?

**Comment by waisbrot** [comment]
A warning would be nice. I'm not sure it's simple, though, since you'd have to get inside the YAML interpreter.

**Comment by bgilbert** [comment]
https://github.com/coreos/fcct/pull/156 added a heuristic warning if the file mode appears to have been specified in decimal.

**Comment by waisbrot** [comment]
That's a nice improvement! I think it addresses the underlying problem pretty well.
