### ISSUE TITLE
gpg verify instructions don't work

### ISSUE THREAD

**Issue by kparal** [coreos/fcct#13]
Getting started doc says:
```
Download the latest version of fcct and the detached signature from the releases page. Verify it with gpg:
gpg --verify <fcct binary> <detached sig>
```
However:
```
$ gpg --verify fcct-x86_64-unknown-linux-gnu fcct-x86_64-unknown-linux-gnu.asc 
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
```
So it seems that those two files should be swapped:
```
$ gpg --verify fcct-x86_64-unknown-linux-gnu.asc fcct-x86_64-unknown-linux-gnu
gpg: Signature made Thu 11 Jul 2019 12:46:56 AM CEST
gpg:                using RSA key 9CEB8FE6B4F1E9E752F61C82CDDE268EBB729EC7
gpg: Can't check signature: No public key
```
That works better, but complains about no public key. I'm not very fluent with gpg, so I might be doing something wrong.

**Comment by sgreene570** [comment]
#11 fixed the ordering of the signature file in the readme, so you are correct about needing to flip the two files.  
To resolve that public key, try running ` gpg2 --receive-keys  9CEB8FE6B4F1E9E752F61C82CDDE268EBB729EC7`

**Comment by sgreene570** [comment]
also make sure you have imported the CoreOS application public signing key from here

http://coreos.com/security/

**Comment by kparal** [comment]
OK, thanks. It might be a good idea to link this in the doc, because a lot of people will have no idea about these prerequisite steps.
