### ISSUE TITLE
RFE: Read fcc file from std in

### ISSUE THREAD

**Issue by mitchellmaler** [coreos/fcct#133]
Would like to be able to pass the file in stdin instead of having to pass a file path.

`cat fcc.yml | fcct --scrict --`

When I try this today I just get the standard "Error translating config: Error parsing variant. Variant must be specified"

**Comment by bgilbert** [comment]
You can do this with just `fcct` (or `fcct --strict`, etc).  Your FCC may not be valid.  Could you post its contents?

**Comment by mitchellmaler** [comment]
@bgilbert Oh jeez you are right. I create docker aliases to run fcct and didn't set the interactive flag. (-i/--interactive). Will close this.
