### ISSUE TITLE
LUKS not supported?

### ISSUE THREAD

**Issue by rugk** [coreos/fcct#138]
Even if I use `v1.2.0-experimental`, the [example from the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_encrypted_storage_luks) seems not to be supported:
```yml
variant: fcos
# version: 1.1.0
version: 1.2.0-experimental
storage:
  luks:
    - name: root
      device: /dev/disk/by-partlabel/root
      clevis:
        tpm2: true
      wipe_volume: true
  filesystems:
    - device: /dev/mapper/root
      format: btrfs
      wipe_filesystem: true
      label: root
```

```sh
$ fcct --pretty --strict  < coreos-config/test.yml
Error translating config: yaml: unmarshal errors:
  line 5: field luks not found in type v0_3_exp.Storage
$ fcct -V
Fedora CoreOS Config Transpiler 0.6.0
```

**Comment by arithx** [comment]
Ah, there hasn't been an FCCT release since the LUKS code has landed, in the interim if you build from current master you will be able to use it. I'll throw cutting a new release into my todo list once the Ignition spec bump has landed.

**Comment by bgilbert** [comment]
FCCT 0.7.0 includes stable spec 1.2.0, which has full LUKS support.
