### ISSUE TITLE
provide a rpm in Fedora

### ISSUE THREAD

**Issue by kparal** [coreos/fcct#14]
Instead of downloading binaries from github and manually checking for updates, it would be much more convenient for Fedora users to install `fcct` from a standard repository. Is that planned? Thanks.

**Comment by lucab** [comment]
Similar suggestion: https://github.com/coreos/fcct/issues/19

**Comment by cgwalters** [comment]
I have a bigger proposal in the commit message in https://github.com/coreos/coreos-assembler/pull/670

**Comment by bgilbert** [comment]
[Package review request](https://bugzilla.redhat.com/show_bug.cgi?id=1794832).

**Comment by bgilbert** [comment]
Package added to Rawhide and submitted to Bodhi for F31.  The F30 build [failed](https://koji.fedoraproject.org/koji/taskinfo?taskID=41308606) with an error implying a compatibility problem with the F30 RPM macros; I'm not pursuing that further for now.

Thanks for reporting!
