### ISSUE TITLE
fcct pod cannot translate fcos variant with version 1.2.0

### ISSUE THREAD

**Issue by joyartoun** [coreos/fcct#147]
Hi, I am using variant fcos with version 1.1.0. I am trying to change to variant 1.2.0 but the fcct pod doesnt seem to work with that version.

 Error translating config: No translator exists for variant fcos with version 1.2.0

Any plans on pathing the pod soon?

BR
Joy

**Comment by lucab** [comment]
@joyartoun thanks for the report, but you forgot to mention which container image version you are using.

`quay.io/coreos/fcct:release` (i.e. 0.7.0, released yesterday) should be already fine.

**Comment by joyartoun** [comment]
Hi @lucab , Sorry for this. You are completely correct. My automation script did not download the latest release of the image. When I pulled the image manually it worked.

Thanks!
