### ISSUE TITLE
Nesting for `trees` entry incorrect for specification v1.2 and v1.3

### ISSUE THREAD

**Issue by deuill** [coreos/fcct#181]
Hi, I was trying to implement embedding of a file-tree via the `trees` directive, and was getting strange errors, e.g.:

```
Error translating config: yaml: unmarshal errors:
  line 3: field trees not found in type v1_3.Config
```

Turns out the specifications for versions 1.2 and 1.3 of FCCT have the `trees` field documented with incorrect nesting, i.e. they have the field as a root field, when it should be a sub-field of `storage`:

https://github.com/coreos/fcct/blame/master/docs/config-fcos-v1_2.md#L159
https://github.com/coreos/fcct/blame/master/docs/config-fcos-v1_3.md#L159

Seems like a natural mistake to make, as the structure of the fields is pretty hard to scan in both raw and rendered formats (both on Github and on the https://coreos.github.io/fcct) site. I wonder if a section-subsection formatting might work better?

**Comment by deuill** [comment]
Hm, in scanning the file again, the issue might be the indentation on the `luks` field above, which is one space instead of two, and which is similarly mis-rendered.

**Comment by bgilbert** [comment]
Whoops, thanks for pointing this out!  #182 should fix it.

You're right that the specs aren't super-easy to read.  We have some pretty deep nesting, so I don't know if section headings are the way to go, but we could probably tweak the rendering to make the levels more distinctive.  I've filed #183 for that.
