### ISSUE TITLE
releng: get rid of binaries on github

### ISSUE THREAD

**Issue by lucab** [coreos/fcct#19]
https://github.com/coreos/fcct/releases/tag/v0.1.0 comes with pre-built binaries for 4 platforms/architectures, with signatures.

I'd suggest to get rid of all those, and just release the source code.
We can then wire-in a container autobuilder (e.g. on quay.io), and point people to the container image.
Downstream distributions are still encouraged to package this (as deb/rpm/msi/whatever), and build for how many architectures they want.

**Comment by ajeddeloh** [comment]
I don't think getting rid of them is a great idea, though I do agree we should support container builds and downstream packagers.

**Comment by ajeddeloh** [comment]
`quay.io/coreos/fcct` is now building off master. We'll tag the next release there. Given that there is another separate issue for creating a fedora rpm, I'll close this one out once:

 - [ ] A release is tagged on quay
 - [ ] Docs are updated to point there
