### ISSUE TITLE
Can't create ign file using --output parameter

### ISSUE THREAD

**Issue by ajohnsc** [coreos/fcct#28]
```
./fcct-x86_64-unknown-linux-gnu -strict -pretty -input coreos.yml -output ~/coreos.ign

failed to open /home/aj/coreos.ign: open /home/aj/coreos.ign: no such file or directory
```

and if i try creating a file before hand
```
./fcct-x86_64-unknown-linux-gnu -strict -pretty -input coreos.yml -output ~/coreos.ign

Failed to write config to /home/aj/coreos.ign: write /home/aj/coreos.ign: bad file descriptor
```

**Comment by ajeddeloh** [comment]
I should have been fixed in https://github.com/coreos/fcct/pull/10. Can you confirm it works with master? If you don't want to build it there's now containers at `quay.io/coreos/fcct` you can use.

**Comment by ajeddeloh** [comment]
Now that 0.2.0 is out I'm going to close this. Please reopen if it is still a problem.
