### ISSUE TITLE
Problem when using Docker image

### ISSUE THREAD

**Issue by walnuss0815** [coreos/fcct#36]
I'd like to use the Docker image to generate the Ignition Config with Gitlab CI. 

Currently my configuration (common.fcc) looks like this:
```
variant: fcos
version: 1.0.0
passwd:
  users:
    - name: core
      password_hash: "<removed>"
```

And my .gitlab-ci.yml looks like this:
```
stages:
  - build

generate_config:
  stage: build
  image: quay.io/coreos/fcct:v0.2.0
  script:
    - mkdir config
    - /usr/local/bin/fcct --strict --pretty --input common.fcc --output config/common.ign
  artifacts:
    name: "config-${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}"
    paths:
      - config/*
```

Every push in my repo triggers a CI build. The build always fails with the following error message:
```
...
Skipping Git submodules setup

Error translating config: Error unmarshaling yaml: yaml: unmarshal errors:
  line 3: cannot unmarshal !!str `set -eo...` into common.Common
Error translating config: Error unmarshaling yaml: yaml: unmarshal errors:
  line 3: cannot unmarshal !!str `set -eo...` into common.Common

ERROR: Job failed: exit code 1
```
But on a local VM I am able to successfully generate the Ignition Config with the same command and config file. How is this possible?

**Comment by lucab** [comment]
> line 3: cannot unmarshal !!str `set -eo...` into common.Common

This sounds like the input given to `fcct` is a shell script. I'd suggest to double-check your pipeline to make sure `common.fcc` has the right content first, before plugging in `fcct`.

**Comment by walnuss0815** [comment]
The Dockerfile only contains the fcct executable. But Gitlab CI seems to need shell to execute the commands. So I've built my own Debian based fcct image and it worked. :)
