### ISSUE TITLE
Users getting lost in using CT 

### ISSUE THREAD

**Issue by shadowbq** [coreos/fcct#39]
Please can someone put a note in the old Repo:
https://github.com/coreos/container-linux-config-transpiler

All the old blogs and links state that people should use the Config-transpiler, and it points to the old CoreOS CT tool. This is now over a year with ZERO commits, and no ISSUE tabs. This causes people to abandon the search for CT. Please talk about the relationship at least between the two projects.

**Comment by ajeddeloh** [comment]
Good call. I opened https://github.com/coreos/container-linux-config-transpiler/pull/166

**Comment by ajeddeloh** [comment]
Closed via that PR
