### ISSUE TITLE
-o option does not overwrite the file

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fcct#42]
When a config yaml file is fed to `fcct` tool such as:
`~/bin/fcct -input test2.yaml -output test2.json -pretty`

a ignition json file is created.  Now, modify the YAML file, say, add an entry to `storage` or change `group/user `info in `passwd`.  Rerun the same above command.  Check the json file - it is incorrect.  The tool tries to in-place modify the JSON instance rather overwrite the file.  I would expect overwrite not update.

**Comment by ajeddeloh** [comment]
Thanks for the report! Fixed in master now.

**Comment by shivarammysore** [comment]
Thanks very much for a quick response!
