### ISSUE TITLE
Document support inline source for files

### ISSUE THREAD

**Issue by J0WI** [coreos/fcct#45]
`fcct` does only support source URLs. The `data` schema has the drawback that everything needs to be urlencoded.
`ct` provides a handy `inline` option:
https://github.com/coreos/container-linux-config-transpiler/blob/50afd07d6e9cb73fbeb0e9c7b7f34c4d29829ffb/doc/examples.md#files

**Comment by spaced** [comment]
sure? just tested and the inline feature works as expected.
related source code: https://github.com/coreos/fcct/blob/master/base/v0_1/translate.go#L58

**Comment by J0WI** [comment]
Is this an [undocumented](https://github.com/coreos/fcct/blob/master/docs/configuration-v1_0.md) feature?

**Comment by spaced** [comment]
kind of. ignition spec does not support it. but fcct translates a
```
contents:
        inline: |
          anytext
```
into
```
"contents":{"source":"data:,anytext"}
```

**Comment by lucab** [comment]
Thanks for report and the followups! I do believe this is indeed an undocumented feature on `fcct` side.
`ct` used to have this feature, and documented at https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/configuration.md.

I'm not sure if @ajeddeloh forgot to add docs for it, or if he wanted to get rid of that but for some reasons forgot the logic in. I'd wait for him to come and double-check in which direction he wants to push this ticket.

**Comment by ajeddeloh** [comment]
Inline is an intended feature. I did just forgot docs, whoops. I'm hijacking this ticket to make it an issue for adding those docs.
