### ISSUE TITLE
Spurious newline is output

### ISSUE THREAD

**Issue by keithy** [coreos/fcct#54]
fcct appears to output an unneccessary newline to STDOUT even when -output is being used.

**Comment by lucab** [comment]
Thanks for the report.
I think this has been already fixed by https://github.com/coreos/fcct/pull/49, which is not part of any release yet though.
@keithy can you maybe compile master and check if it behaves properly? Otherwise, I know @ajeddeloh has an `fcct` release planned soon-ish.

**Comment by bgilbert** [comment]
Works for me; closing.  Please reopen if you're still seeing this on the current version.
