### ISSUE TITLE
Consider tagging a new release

### ISSUE THREAD

**Issue by lucab** [coreos/fcct#56]
We piled up a bunch of changes and bugfixes since the last release, so it would be good to tag a new release soon-ish: https://github.com/coreos/fcct/compare/v0.2.0...master

**Comment by lucab** [comment]
/cc @ajeddeloh 

I know he had this on his radar, but I don't know what's the timing.

**Comment by dustymabe** [comment]
Yeah let's make a new release to get some fixes in?

**Comment by bgilbert** [comment]
Done in https://github.com/coreos/fcct/issues/67.
