### ISSUE TITLE
Add a release tag on Quay

### ISSUE THREAD

**Issue by bgilbert** [coreos/fcct#63]
The [docs for using the container](https://github.com/coreos/fcct/blob/master/docs/getting-started.md#container) require the user to know the current FCCT version, which is inconvenient.

Create a `release` tag, similar to the one for coreos-installer.  Recommend that users use that instead, and update the release process to move the tag.

@jlebon @lucab Any objections?

**Comment by jlebon** [comment]
Yeah, that makes a lot of sense to me!
