### ISSUE TITLE
FCCT doesn't complain about extra command-line arguments

### ISSUE THREAD

**Issue by gabx** [coreos/fcct#69]
My **.yaml** configuration file is named `tth.fcc` and has been written using visual studio and the red hat yaml plugin. When saving the file, visual studio does not split any error. Everything is made from my home directory. I use fcct v 0.3.

```
% ls -al 
....
tth.yaml
% mv tth.yaml tth.fcc
% ls -al 
...
tth.fcc
%podman pull quay.io/coreos/fcct:v0.3.0
%podman run -i --rm quay.io/coreos/fcct:v0.3.0 -pretty -strict tth.fcc transpiled_config.ign
_
```

Nothing happens. The command outputs nothing and after a few minutes, I have to **ctr+c** to quit.
Now:

```
%podman run --rm -v /var/home/gabx/tth.fcc:/config.fcc:z quay.io/coreos/fcct:v0.3.0 -pretty -strict -input /config.fcc > transpiled_config.ign
%ls -al
....
transpiled_config.ign
tth.fcc
```

The command succeeded and I have a proper ignition file. 
No idea why one succeed and not the other one.

**Comment by jlebon** [comment]
```
%podman run -i --rm quay.io/coreos/fcct:v0.3.0 -pretty -strict tth.fcc transpiled_config.ign
```

This isn't using stdin/stdout though, right? See the example invocation in https://github.com/coreos/fcct/blob/master/docs/getting-started.md#container:

```
podman run -i --rm quay.io/coreos/fcct:release -pretty -strict < your_config.fcc > transpiled_config.ign
```

**Comment by gabx** [comment]
so you are telling me the correct command shall place the **.fcc** config in between less/greater symbols **<  >** ? 
I was wondering why these two symbols were placed here. I have been confused.

**Comment by jlebon** [comment]
Yup, exactly! The `<` tells bash to feed the contents of the file specified to the command and `>` tells bash to write the output of the command to the file specified. Check out this page from the Bash manual for more info: https://www.gnu.org/software/bash/manual/html_node/Redirections.html.

**Comment by bgilbert** [comment]
Retitled to reflect what I think is the actual bug here.  It's unusual that FCCT requires an `-input` option for specifying the input file, and if there's a bare filename passed on the command line, FCCT silently ignores it and waits for stdin.

We should fix the latter part, at least.  What would folks think about also deprecating `-input` and reading a bare filename arg instead?

**Comment by jlebon** [comment]
>  What would folks think about also deprecating `-input` and reading a bare filename arg instead?

UX-wise, I agree allowing the input file as positional arg makes sense. Re. deprecation, I like that `-input` is symmetrical to `-output` but then we'd have *three* different ways to specify the input file, so I see where you're coming from too.
