### ISSUE TITLE
file Mode octal to int conversion: 0600 -> 384

### ISSUE THREAD

**Issue by trexx** [coreos/fcct#77]
Using this https://docs.fedoraproject.org/en-US/fedora-coreos/static-ip-config/ as an example where the mode of the file is set to 0600, the resulting mode after translation is  `"mode": 384`

It seems as if there's a conversion to base 10 during translation that results in the value 384.

-Version output
`Fedora CoreOS Config Transpiler 0.4.0`
Tried both linux exe in Ubuntu WSL and native windows exe.

**Comment by trexx** [comment]
Sorry, seems like this is to be expected and was previously under heavy discussion by coreos.

**Comment by lucab** [comment]
Thanks for the report, however I'm not exactly sure what is the issue you are reporting here. 
Are you saying that the final file on disk has (octal) mode `0o0384` in octal? Or are you saying that after transpiling you see a `"mode": 384` in the Ignition configuration?


The former would be a bug, while the latter is expected per Ignition spec, see https://github.com/coreos/ignition/issues/842.

**Comment by strigazi** [comment]
I think the issue is in the docs: https://docs.fedoraproject.org/en-US/fedora-coreos/static-ip-config/

Is `mode: 0600` intended? Given that fcct and ignition expect decimal.
