### ISSUE TITLE
Is `directories` option only to create directory or can I recursively copy?

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fcct#86]
In https://github.com/coreos/fcct/blob/master/docs/configuration-v1_0.md - `storage --> directories` is it used to only create empty directories?  Is there a way to recursively copy a directory say from S3 location

**Comment by bgilbert** [comment]
`directories` only creates empty directories.  You can create a bunch of `directories` and `files` objects to copy a directory tree from S3, but you'd have to list them explicitly; there's currently no way to have Ignition automatically perform the recursion.

**Comment by shivarammysore** [comment]
Got it.  Thanks for clarification.
